FROM buildpack-deps:xenial-scm

ENV NPM_CONFIG_LOGLEVEL info
ENV NODE_VERSION 6.2.0

RUN curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz" \
  && tar -xf "node-v$NODE_VERSION-linux-x64.tar.gz" -C /usr/local --strip-components=1 \
  && rm "node-v$NODE_VERSION-linux-x64.tar.gz" \
  && ln -s /usr/local/bin/node /usr/local/bin/nodejs

RUN \
  apt-get update && \
  apt-get install -y apt-utils && \
  apt-get install -y sudo python2.7 curl git xvfb gcc g++ make libkrb5-dev jq openjdk-8-jre-headless bzip2 libqt4-dev libqtwebkit-dev qt4-qmake && \
  apt-get install -y mongodb-clients redis-tools host && \
  apt-get install -y libgtk2.0-0 libxss1 libgconf2-4 libasound2 graphicsmagick fonts-migmix libxtst6 libnss3
